import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'

// ============================================
// B2B QUOTES API
// File: app/api/b2b/quotes/route.ts
// ============================================

// Lazy-initialized Supabase admin client (avoids build-time errors)
let _supabaseAdmin: ReturnType<typeof createClient> | null = null

function getSupabaseAdmin() {
  if (!_supabaseAdmin) {
    _supabaseAdmin = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )
  }
  return _supabaseAdmin
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const id = searchParams.get('id')
    const partner_id = searchParams.get('partner_id')
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '50')

    // Get single quote by ID
    if (id) {
      const { data, error } = await getSupabaseAdmin()
        .from('tour_quotes')
        .select(`
          *,
          tour_variations (variation_name, variation_code, tier, tour_templates (template_name, template_code, duration_days)),
          b2b_partners (company_name, partner_code, contact_name, email)
        `)
        .eq('id', id)
        .single()

      if (error) throw error
      return NextResponse.json({ success: true, data })
    }

    // List quotes
    let query = getSupabaseAdmin()
      .from('tour_quotes')
      .select(`
        *,
        tour_variations (variation_name, variation_code, tier, tour_templates (template_name, template_code)),
        b2b_partners (company_name, partner_code)
      `)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (partner_id) query = query.eq('partner_id', partner_id)
    if (status) query = query.eq('status', status)

    const { data, error } = await query

    if (error) throw error
    return NextResponse.json({ success: true, data: data || [] })

  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      variation_id,
      partner_id,
      client_name,
      client_email,
      client_phone,
      client_nationality,
      travel_date,
      num_adults = 2,
      num_children = 0,
      // Pre-calculated pricing from UI
      services_snapshot,
      total_cost,
      margin_percent,
      margin_amount,
      selling_price,
      price_per_person,
      // New fields
      tour_leader_included = false,
      tour_leader_cost,
      single_supplement,
      is_eur_passport = true,
      season,
      // Other
      currency = 'EUR',
      valid_days = 30,
      notes,
      created_by
    } = body

    if (!variation_id) {
      return NextResponse.json({ success: false, error: 'variation_id is required' }, { status: 400 })
    }

    if (!total_cost || !selling_price) {
      return NextResponse.json({ success: false, error: 'Pricing data is required' }, { status: 400 })
    }

    // Calculate valid_until date
    const validUntil = new Date()
    validUntil.setDate(validUntil.getDate() + valid_days)

    // Insert quote - quote_number is auto-generated by trigger
    const { data: quote, error } = await getSupabaseAdmin()
      .from('tour_quotes')
      .insert({
        variation_id,
        partner_id: partner_id || null,
        client_name,
        client_email,
        client_phone,
        client_nationality,
        travel_date,
        num_adults,
        num_children,
        services_snapshot,
        total_cost,
        margin_percent,
        margin_amount,
        selling_price,
        price_per_person,
        currency,
        tour_leader_included,
        tour_leader_cost,
        single_supplement,
        is_eur_passport,
        season,
        status: 'draft',
        valid_until: validUntil.toISOString().split('T')[0],
        notes,
        created_by
      } as any)
      .select()
      .single()

    if (error) {
      console.error('Error creating quote:', error)
      return NextResponse.json({ success: false, error: error.message }, { status: 500 })
    }

    const q = quote as any
    console.log('✅ Quote created:', q.quote_number)
    return NextResponse.json({ success: true, data: q }, { status: 201 })

  } catch (error: any) {
    console.error('Error in POST /api/b2b/quotes:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}

export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    const { id, ...updates } = body

    if (!id) {
      return NextResponse.json({ success: false, error: 'id is required' }, { status: 400 })
    }

    updates.updated_at = new Date().toISOString()

    const { data, error } = await getSupabaseAdmin()
      .from('tour_quotes')
      .update(updates)
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return NextResponse.json({ success: true, data })

  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}

export async function DELETE(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const id = searchParams.get('id')

  if (!id) {
    return NextResponse.json({ success: false, error: 'id is required' }, { status: 400 })
  }

  try {
    const { error } = await getSupabaseAdmin()
      .from('tour_quotes')
      .delete()
      .eq('id', id)

    if (error) throw error
    return NextResponse.json({ success: true })

  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}