import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { ScreenshotPlaceholder, Tip, DocScreenshot } from '../layout'

export default function B2BQuotesPage() {
  return (
    <div>
      {/* Breadcrumb */}
      <nav className="flex items-center gap-2 text-sm text-gray-500 mb-6">
        <Link href="/docs" className="hover:text-primary-600 transition-colors">Docs</Link>
        <ChevronRight className="w-4 h-4" />
        <span className="text-gray-900 font-medium">B2B Quotes</span>
      </nav>

      <h1 className="text-3xl font-bold text-gray-900 mb-4">B2B Quotes</h1>
      <p className="text-gray-600 mb-8">
        B2B Quotes are saved pricing snapshots that you can share with tour operator partners. Each quote captures a specific calculation from the B2B Price Calculator with all service details, ready for PDF export and partner distribution. Like the calculator, this area is restricted to admin and manager roles.
      </p>

      {/* Single store */}
      <section className="mb-10">
        <Tip>
          <strong>One list for every B2B quote:</strong> whether a quote was saved from the <strong>B2B Price Calculator</strong>,
          from the <strong>Pricing Grid</strong> in B2B mode, or generated by the AI, it appears under <strong>B2B &rarr; Quotes</strong> &mdash;
          the list documented on this page.
        </Tip>
      </section>

      {/* Creating a Quote */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Creating a Quote</h2>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li>Go to the <strong>B2B Price Calculator</strong> and calculate a price</li>
          <li>Click <strong>Save as Quote</strong></li>
          <li>Optionally fill in:
            <ul className="list-disc list-inside ml-6 mt-2 space-y-1 text-gray-600">
              <li><strong>Partner</strong> &mdash; Select the tour operator from your Partners list</li>
              <li><strong>Client Name</strong> &mdash; End client name if known</li>
              <li><strong>Email &amp; Phone</strong> &mdash; Client contact details</li>
              <li><strong>Nationality</strong> &mdash; For passport-type reference</li>
              <li><strong>Notes</strong> &mdash; Special requests or conditions</li>
            </ul>
          </li>
          <li>Click <strong>Save Quote</strong></li>
        </ol>
        <p className="text-gray-600 mt-3">
          The quote is assigned a unique reference number and captures the full pricing snapshot: services, rates, margin, and totals. A confirmation banner shows the reference with a <strong>View Quote</strong> link.
        </p>
        <ScreenshotPlaceholder caption="Save Quote dialog with partner selection, client details, and notes" />
      </section>

      {/* Partners */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Partners</h2>
        <p className="text-gray-600 mb-3">
          B2B partners are managed on their own page: <strong>B2B &rarr; Partners</strong>. Partners are separate from your regular contacts &mdash; each partner record can carry a <strong>default margin percentage</strong> that is applied automatically when you price work for that partner, overriding any manually entered margin.
        </p>
        <DocScreenshot src="/docs/b2b-quotes/partners.jpg" alt="Partners page with partner records and default margin percentages" />
      </section>

      {/* Viewing Quotes */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Viewing Quotes</h2>
        <p className="text-gray-600 mb-3">
          Navigate to <strong>B2B &rarr; Quotes</strong> in the sidebar. The quotes page shows:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li><strong>Stats Row</strong> &mdash; Total, Draft, Sent, and Accepted counts</li>
          <li><strong>Quote Table</strong> &mdash; All saved quotes with reference, tour, partner, and pricing details</li>
          <li><strong>Status Badges</strong> &mdash; Draft, Sent, Accepted, Rejected, or Expired</li>
          <li><strong>Status Filter</strong> &mdash; Filter by Draft, Sent, Accepted, or Rejected</li>
          <li><strong>Search</strong> &mdash; Matches reference code, tour name, partner name, or client name</li>
          <li><strong>Row Actions</strong> &mdash; View, download PDF, or delete a quote</li>
        </ul>
        <DocScreenshot src="/docs/b2b-quotes/quotes-list.jpg" alt="B2B Quotes table with stats row, status filter, and View/PDF/Delete actions" />
      </section>

      {/* Quote Details */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Quote Details</h2>
        <p className="text-gray-600 mb-3">
          Click a quote to see its full details:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li><strong>Tour Info</strong> &mdash; Template name, variation, tier badge, plus Duration, Travelers, Travel Date, and Season</li>
          <li><strong>Services Included</strong> &mdash; The complete service breakdown as calculated at quote time</li>
          <li><strong>Pricing</strong> &mdash; Total cost, margin, selling price, per person</li>
          <li><strong>Notes</strong> and <strong>Client Details</strong> &mdash; Contact information and any special conditions</li>
          <li><strong>Update Status</strong> &mdash; Buttons to move the quote between Draft, Sent, Accepted, and Rejected</li>
          <li><strong>Valid Until</strong> &mdash; The quote&apos;s expiry date; expired quotes are flagged in the list</li>
        </ul>
      </section>

      {/* PDF Export */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">PDF Export</h2>
        <p className="text-gray-600 mb-3">
          Click the PDF action to generate a professional B2B quote document. PDFs are rendered on the server for consistent output and include:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li>Your company branding and logo</li>
          <li>Quote reference number and date</li>
          <li>Tour details and services</li>
          <li>Pricing summary</li>
          <li>Terms and conditions</li>
        </ul>
      </section>

      {/* Navigation */}
      <div className="mt-12 pt-6 border-t border-gray-200 flex justify-between">
        <Link href="/docs/tour-programs" className="flex items-center gap-2 text-sm text-gray-600 hover:text-primary-600 transition-colors">
          <ChevronRight className="w-4 h-4 rotate-180" />
          Tour Programs Manager
        </Link>
        <Link href="/docs/bookings" className="flex items-center gap-2 text-sm text-gray-600 hover:text-primary-600 transition-colors">
          Next: Bookings
          <ChevronRight className="w-4 h-4" />
        </Link>
      </div>
    </div>
  )
}
