// =====================================================================
// Railway Infrastructure as Code — replaces railway.toml + railway.cron-*.toml
// =====================================================================
// Generated by `railway config pull` (imports Railway's LIVE state), then
// hand-corrected. Do NOT regenerate blindly: `pull` can only export what
// Railway has stored, and two of these four services keep their start command
// ONLY in a config file, so a fresh import drops them. See the comments below.
//
// `railway config migrate` is NOT usable here — it reads only the canonical
// railway.toml, emits a single service, and ignores every railway.cron-*.toml.
//
// Secrets are `preserve()`: values stay in Railway and are never written here.
//
// Workflow:  railway config plan     (diff, changes nothing)
//            railway config apply    (applies, clears Config File settings)
// =====================================================================

import { defineRailway, github, preserve, project, service } from "railway/iac";

export default defineRailway(() => {
  const autouraSaas = github("desertcanvasart-dotcom/autoura-saas", { checkSuites: false });

  const AgentMemoryCron = service("Agent memory cron", {
    source: autouraSaas,
    start: "npm run cron:agent-memory",
    replicas: { "asia-southeast1-eqsg3a": 1 },
    deploy: { cronSchedule: "0 2 * * *", restartPolicyType: "NEVER" },
    networking: { privateNetworkEndpoint: "agent-memory-cron" },
    env: {
      APP_URL: preserve(),
      CRON_SECRET: preserve(),
    },
  });
  const RemindersCron = service("Reminders Cron", {
    source: autouraSaas,
    // NOT imported from Railway — this service has no stored start command;
    // it comes from railway.cron-reminders.toml, which stops being read on
    // 2026-12-01. Written out here so the migration is behaviour-preserving
    // rather than the thing that breaks it.
    start: "npm run cron:reminders",
    replicas: { "asia-southeast1-eqsg3a": 1 },
    deploy: { cronSchedule: "0 6 * * *", restartPolicyType: "NEVER" },
    networking: { privateNetworkEndpoint: "reminders-cron" },
    env: {
      APP_URL: preserve(),
      CRON_SECRET: preserve(),
    },
  });
  const getAutoura = service("get-autoura", {
    source: autouraSaas,
    // Same as above: not stored on the service, supplied today by railway.toml.
    // This is the live site — applying without it would clear the config-file
    // setting and leave the web service with no start command at all.
    start: "npm run start",
    replicas: { "asia-southeast1-eqsg3a": 1 },
    domains: ["getautoura.net", "www.getautoura.net"],
    networking: { privateNetworkEndpoint: "autoura-saas" },
    env: {
      ANTHROPIC_API_KEY: preserve(),
      BUSINESS_EMAIL: preserve(),
      BUSINESS_NAME: preserve(),
      BUSINESS_WEBSITE: preserve(),
      BUSINESS_WHATSAPP: preserve(),
      CONCIERGE_WEBHOOK_SECRET: preserve(),
      CONCIERGE_WEBHOOK_TENANT_ID: preserve(),
      CRON_SECRET: preserve(),
      ENABLE_WHATSAPP_AUTO_SEND: preserve(),
      ENABLE_WHATSAPP_STATUS_UPDATES: preserve(),
      EXCHANGE_RATE_API_KEY: preserve(),
      GMAIL_APP_PASSWORD: preserve(),
      GMAIL_USER: preserve(),
      GOOGLE_CLIENT_ID: preserve(),
      GOOGLE_CLIENT_SECRET: preserve(),
      GOOGLE_REDIRECT_URI: preserve(),
      NEXT_PUBLIC_APP_URL: preserve(),
      NEXT_PUBLIC_SUPABASE_ANON_KEY: preserve(),
      NEXT_PUBLIC_SUPABASE_URL: preserve(),
      OAUTH_STATE_SECRET: preserve(),
      OPENAI_API_KEY: preserve(),
      RESEND_API_KEY: preserve(),
      RESEND_FROM_EMAIL: preserve(),
      SAWA_SYNC_SECRET: preserve(),
      STRIPE_SECRET_KEY: preserve(),
      STRIPE_WEBHOOK_SECRET: preserve(),
      SUPABASE_SERVICE_ROLE_KEY: preserve(),
      SUPER_ADMIN_EMAILS: preserve(),
      TWILIO_ACCOUNT_SID: preserve(),
      TWILIO_API_KEY: preserve(),
      TWILIO_API_SECRET: preserve(),
      TWILIO_AUTH_TOKEN: preserve(),
      TWILIO_WHATSAPP_FROM: preserve(),
      TWILIO_WHATSAPP_NUMBER: preserve(),
      WHATSAPP_AI_ENABLED: preserve(),
    },
  });
  const cronexchangeRates = service("cron:exchange-rates", {
    source: autouraSaas,
    build: "",
    start: "npm run cron:exchange-rates",
    replicas: { "asia-southeast1-eqsg3a": 1 },
    deploy: { cronSchedule: "0 1 * * *", restartPolicyType: "NEVER" },
    networking: { privateNetworkEndpoint: "compassionate-heart" },
    env: {
      APP_URL: preserve(),
      CRON_SECRET: preserve(),
    },
  });

  return project("Autoura multi-tenant", {
    resources: [AgentMemoryCron, RemindersCron, getAutoura, cronexchangeRates],
  });
});
