-- ============================================================================
-- 392 — Operations tasks become one checklist per kind of service
-- ============================================================================
-- An itinerary's operations tasks are now generated by plain code
-- (lib/tasks/itinerary-tasks.ts), not by a model: ONE task per category — all
-- the hotels, Nile cruises and sleeper trains in one Accommodation task, every
-- transfer in one Transportation task, and so on. Each task carries its
-- services as checklist rows that staff tick as booked, with a confirmation
-- number. Generating again SYNCS the tasks instead of adding duplicates.
--
-- service_type        — the task's category ('accommodation', 'flight', …).
--                       NULL on a task made by hand; generation never touches
--                       those.
-- generation_snapshot — { header, lines[] }: what the task listed when last
--                       generated, compared on the next run to tell an
--                       unchanged task from one whose itinerary moved.
-- checklist           — [{ key, day_from, day_to, date_from, date_to, city,
--                         name, quantity, nights, supplier, notes, unpriced?,
--                         booked, confirmation, booked_at, is_new?, removed? }]
--                       The key is the service line as text; a row whose key
--                       is unchanged keeps its tick across regenerations.
--
-- Additive and replay-safe: three nullable columns and an index.

BEGIN;

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS service_type text,
  ADD COLUMN IF NOT EXISTS generation_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS checklist jsonb;

-- The generator looks up an itinerary's generated tasks by category.
CREATE INDEX IF NOT EXISTS idx_tasks_linked_service_type
  ON public.tasks (linked_type, linked_id, service_type)
  WHERE service_type IS NOT NULL;

COMMIT;
